{{ HTML::linkAction('FrontController@index', 'Front') }} 
{{ HTML::linkAction('NewsController@index', 'News') }} 
{{ HTML::linkAction('BlogController@index', 'Blogs') }} 
{{ HTML::linkAction('ForumController@index', 'Forums') }} 
{{ HTML::linkAction('ExpatController@index', 'Expats') }} 
{{ HTML::linkAction('BuysellController@index', 'Buysell') }} 
{{ HTML::linkAction('TravelmateController@index', 'Travelmates') }} 
{{ HTML::linkAction('MiscController@index', 'Misc') }} 
{{ HTML::linkAction('ImageController@index', 'Images') }} 
{{ HTML::linkAction('FlightController@index', 'Flights') }} 
{{ HTML::linkAction('OfferController@index', 'Offers') }}
